Repository michelroegl-brunner/ProxmoxVE, pull requests merged in 2025-02, with the labels that each got.

#69 Update api.func
  misc/api.func
Labels: api, update script

#123 Update 2fauth.sh
  ct/2fauth.sh
Labels: update script, bugfix, feature

#126 Update 2fauth.sh
  ct/2fauth.sh
Labels: update script

#127 Update adventurelog.sh
  ct/adventurelog.sh
Labels: update script, feature

#129 Update agentdvr.sh
  ct/agentdvr.sh
Labels: update script

#131 Update alpine-nextcloud.sh
  ct/alpine-nextcloud.sh
Labels: update script, general

#134 Update alpine-zigbee2mqtt.sh
  ct/alpine-zigbee2mqtt.sh
Labels: update script, general

#133 Update adguard.sh
  ct/adguard.sh
Labels: update script, bugfix

#136 Update CONTRIBUTING.md
  .github/CONTRIBUTOR_AND_GUIDES/CONTRIBUTING.md
Labels: maintenance

#141 Update main.go
  api/main.go
Labels: api, maintenance

#140 Update adventurelog.sh
  ct/adventurelog.sh
Labels: update script, breaking_change

#143 Update build.func
  misc/build.func
Labels: maintenance, core, high risk

#146 Update robots.ts
  frontend/src/app/robots.ts
Labels: website, breaking change

#145 Update page.tsx
  frontend/src/app/page.tsx
Labels: bugfix, website

#165 Update actualbudget-install.sh
  install/actualbudget-install.sh
Labels: update script

#166 Revert "Update actualbudget-install.sh"
  install/actualbudget-install.sh
Labels: update script

#174 Update go.sum
  api/go.sum
Labels: api, maintenance

#179 Revert "Update agentdvr.sh"
  ct/agentdvr.sh
Labels: update script

#180 Update adventurelog.sh
  ct/adventurelog.sh
Labels: update script

#193 Revert "Update adguard.sh"
  ct/adguard.sh
Labels: update script

#196 Update go.mod
  api/go.mod
Labels: api, maintenance

#199 Update agentdvr.sh
  ct/agentdvr.sh
Labels: update script
